X_train_pth: C:/Users/user/PycharmProjects/Multimodal_22/data/cite_seen_2/cite_train_x.h5ad
y_train_pth: C:/Users/user/PycharmProjects/Multimodal_22/data/cite_seen_2/cite_train_y_norm.h5ad
X_test_pth: C:/Users/user/PycharmProjects/Multimodal_22/data/cite_seen_2/cite_test_x.h5ad
y_test_pth: C:/Users/user/PycharmProjects/Multimodal_22/data/cite_seen_2/cite_test_y_norm.h5ad
X_train_processed_dir: C:/Users/user/PycharmProjects/Multimodal_22/data/cite_seen_2/p_train_x
y_train_processed_dir: C:/Users/user/PycharmProjects/Multimodal_22/data/cite_seen_2/p_train_y
X_test_processed_dir: C:/Users/user/PycharmProjects/Multimodal_22/data/cite_seen_2/p_test
result_dir_pth: C:/Users/user/PycharmProjects/Multimodal_22/data/cite_seen_2/results/
mem_file_name: mem_profile.txt
name: seurat